Respect the thread-specific locale on MacOS X.

diff --git a/gettext-tools/tests/gettext-6 b/gettext-tools/tests/gettext-6
--- a/gettext-tools/tests/gettext-6
+++ b/gettext-tools/tests/gettext-6
@@ -7,30 +7,29 @@
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
 
-# This test works only on glibc systems.
+# This test works only on glibc and MacOS X systems.
+: ${host_os=unknown}
 : ${GLIBC2=no}
-test "$GLIBC2" = yes || {
-  echo "Skipping test: not a glibc system"
+{ case "$host_os" in
+    *-gnu*) test "$GLIBC2" = yes ;;
+    darwin*) true ;;
+    *) false ;;
+  esac
+} || {
+  echo "Skipping test: not a glibc or Mac OS X system"
   exit 77
 }
 
 # This test works only on systems that have a de_DE and fr_FR locale installed.
-LC_ALL=de_DE ./testlocale || {
+missing_locale=`./gettext-6-prg 1`
+if test -n "$missing_locale"; then
   if test -f /usr/bin/localedef; then
-    echo "Skipping test: locale de_DE not installed"
+    echo "Skipping test: locale ${missing_locale} not installed"
   else
-    echo "Skipping test: locale de_DE not supported"
+    echo "Skipping test: locale ${missing_locale} not supported"
   fi
   exit 77
-}
-LC_ALL=fr_FR ./testlocale || {
-  if test -f /usr/bin/localedef; then
-    echo "Skipping test: locale fr_FR not installed"
-  else
-    echo "Skipping test: locale fr_FR not supported"
-  fi
-  exit 77
-}
+fi
 
 tmpfiles="$tmpfiles de_DE fr_FR"
 test -d de_DE || mkdir de_DE
@@ -55,7 +54,7 @@ tmpfiles="$tmpfiles gt-6.out"
 case $? in
   0) ;;
   77)
-    echo "Skipping test: not a glibc 2.3 system"
+    echo "Skipping test: not a glibc >= 2.3 or MacOS X >= 10.5 system"
     rm -fr $tmpfiles; exit 77
     ;;
 esac
