Avoid lang-vala failure on macOS with MacPorts.
* gettext-tools/tests/lang-vala: Skip the test if the valac invocation reports
that <glib.h> is not installed.

diff --git a/gettext-tools/tests/lang-vala b/gettext-tools/tests/lang-vala
--- a/gettext-tools/tests/lang-vala
+++ b/gettext-tools/tests/lang-vala
@@ -23,7 +23,12 @@ test $? -le 1 \
 
 : ${VALAC=valac}
 ${VALAC} --Xcc=-DGETTEXT_PACKAGE=\"prog\" prog.vala 2>prog.err \
-  || { cat prog.err 1>&2; Exit 1; }
+  || { if grep "fatal error: 'glib\.h' file not found" < prog.err > /dev/null; then
+         echo "Skipping test: valac installation incomplete"; Exit 77
+       else
+         cat prog.err 1>&2; Exit 1
+       fi
+     }
 
 : ${XGETTEXT=xgettext}
 ${XGETTEXT} -o prog.tmp --omit-header --no-location prog.vala || Exit 1
