tests: Remove unnecessary tempfile cleanup code
Cleanup code like "rm -fr $tmpfiles" are no longer needed, since
'init.sh' takes care of that.

diff --git a/gettext-tools/tests/lang-bash b/gettext-tools/tests/lang-bash
--- a/gettext-tools/tests/lang-bash
+++ b/gettext-tools/tests/lang-bash
@@ -10,10 +10,6 @@
 # output when accessing any .mo file not generated from a .po file in UTF-8
 # encoding.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.bash"
 cat <<\EOF > prog.bash
 #! /bin/bash
 
@@ -31,18 +27,15 @@ $echo $"'Your command, please?', asked the waiter."
 $echo "`eval_ngettext "a piece of cake" "\\$n pieces of cake" $n`"
 EOF
 
-tmpfiles="$tmpfiles l-bash-prog.tmp l-bash-prog.pot l-bash-prog.err"
 : ${XGETTEXT=xgettext}
 LC_MESSAGES=C LC_ALL= \
 ${XGETTEXT} -o l-bash-prog.tmp --omit-header --no-location prog.bash \
   >l-bash-prog.err 2>&1
 result=$?
 cat l-bash-prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
-test $result = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-bash-prog.tmp > l-bash-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+test $result = 0 || { exit 1; }
+LC_ALL=C tr -d '\r' < l-bash-prog.tmp > l-bash-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-bash-prog.ok"
 cat <<\EOF > l-bash-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -57,7 +50,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-bash-prog.ok l-bash-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-bash-fr.po"
 cat <<\EOF > l-bash-fr.po
 msgid ""
 msgstr ""
@@ -75,17 +67,13 @@ msgstr[0] "un morceau de gateau"
 msgstr[1] "$n morceaux de gateau"
 EOF
 
-tmpfiles="$tmpfiles l-bash-fr.po.tmp l-bash-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-bash-fr.po.tmp l-bash-fr.po l-bash-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-bash-fr.po.tmp > l-bash-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-bash-fr.po.tmp l-bash-fr.po l-bash-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-bash-fr.po.tmp > l-bash-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-bash-fr.po l-bash-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-bash"
 test -d l-bash || mkdir l-bash
 test -d l-bash/fr || mkdir l-bash/fr
 test -d l-bash/fr/LC_MESSAGES || mkdir l-bash/fr/LC_MESSAGES
@@ -95,10 +83,10 @@ ${MSGFMT} -o l-bash/fr/LC_MESSAGES/prog.mo l-bash-fr.po
 
 # Test for presence of bash version 2.0 or newer.
 (bash -c :) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: bash not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: bash not found"; exit 77; }
 case `bash -c 'echo $BASH_VERSION'` in
   [2-9].*) ;;
-  *) echo "Skipping test: bash version too old"; rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: bash version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -126,10 +114,9 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles l-bash-prog.nok l-bash-prog.ok l-bash-prog.oku l-bash-prog.out"
 # Expected result when bash is built without i18n support.
 cat <<\EOF > l-bash-prog.nok
 'Your command, please?', asked the waiter.
@@ -152,7 +139,7 @@ if test $LOCALE_FR != none; then
   : ${DIFF=diff}
   ${DIFF} l-bash-prog.nok l-bash-prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    rm -fr $tmpfiles; exit 77
+    exit 77
   }
   ${DIFF} l-bash-prog.ok l-bash-prog.out || exit 1
 fi
@@ -161,11 +148,9 @@ if test $LOCALE_FR_UTF8 != none; then
   : ${DIFF=diff}
   ${DIFF} l-bash-prog.nok l-bash-prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    rm -fr $tmpfiles; exit 77
+    exit 77
   }
   ${DIFF} l-bash-prog.oku l-bash-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-guile b/gettext-tools/tests/lang-guile
--- a/gettext-tools/tests/lang-guile
+++ b/gettext-tools/tests/lang-guile
@@ -5,10 +5,6 @@
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: guile.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.scm"
 cat <<\EOF > prog.scm
 (use-modules (ice-9 format))
 
@@ -25,14 +21,10 @@ cat <<\EOF > prog.scm
 (format #t "~A~%" (format #f (gettext "~A is replaced by ~A.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles l-guile-prog.tmp l-guile-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-guile-prog.tmp --omit-header --no-location prog.scm
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-guile-prog.tmp > l-guile-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-guile-prog.tmp --omit-header --no-location prog.scm || exit 1
+LC_ALL=C tr -d '\r' < l-guile-prog.tmp > l-guile-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-guile-prog.ok"
 cat <<EOF > l-guile-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -51,7 +43,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-guile-prog.ok l-guile-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-guile-fr.po"
 cat <<\EOF > l-guile-fr.po
 msgid ""
 msgstr ""
@@ -74,17 +65,13 @@ msgid "~A is replaced by ~A."
 msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
-tmpfiles="$tmpfiles l-guile-fr.po.tmp l-guile-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-guile-fr.po.tmp l-guile-fr.po l-guile-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-guile-fr.po.tmp > l-guile-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-guile-fr.po.tmp l-guile-fr.po l-guile-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-guile-fr.po.tmp > l-guile-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-guile-fr.po l-guile-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-guile"
 test -d l-guile || mkdir l-guile
 test -d l-guile/fr || mkdir l-guile/fr
 test -d l-guile/fr/LC_MESSAGES || mkdir l-guile/fr/LC_MESSAGES
@@ -94,10 +81,10 @@ ${MSGFMT} -o l-guile/fr/LC_MESSAGES/prog.mo l-guile-fr.po
 
 # Test for presence of guile version 1.7 or newer.
 (guile --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: guile not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: guile not found"; exit 77; }
 case `guile --version | sed -e 1q | sed -e 's/^[^0-9]*//'` in
   0.* | 1.[0-6] | 1.[0-6].* )
-    echo "Skipping test: guile version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: guile version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -125,10 +112,9 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles l-guile-prog.ok l-guile-prog.oku l-guile-prog.out l-guile-prog.err"
 : ${DIFF=diff}
 cat <<\EOF > l-guile-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -153,7 +139,5 @@ if test $LOCALE_FR_UTF8 != none; then
   grep -v '^;;;' l-guile-prog.err 1>&2
   ${DIFF} l-guile-prog.oku l-guile-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-librep b/gettext-tools/tests/lang-librep
--- a/gettext-tools/tests/lang-librep
+++ b/gettext-tools/tests/lang-librep
@@ -5,10 +5,6 @@
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: librep.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.jl"
 cat <<\EOF > prog.jl
 (require 'rep.i18n.gettext)
 
@@ -21,14 +17,10 @@ cat <<\EOF > prog.jl
         (format nil (_ "%s is replaced by %s.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles l-librep-prog.tmp l-librep-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-librep-prog.tmp --omit-header --no-location prog.jl
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-librep-prog.tmp > l-librep-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-librep-prog.tmp --omit-header --no-location prog.jl || exit 1
+LC_ALL=C tr -d '\r' < l-librep-prog.tmp > l-librep-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-librep-prog.ok"
 cat <<EOF > l-librep-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -41,7 +33,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-librep-prog.ok l-librep-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-librep-fr.po"
 cat <<\EOF > l-librep-fr.po
 msgid ""
 msgstr ""
@@ -57,17 +48,13 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles l-librep-fr.po.tmp l-librep-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-librep-fr.po.tmp l-librep-fr.po l-librep-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-librep-fr.po.tmp > l-librep-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-librep-fr.po.tmp l-librep-fr.po l-librep-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-librep-fr.po.tmp > l-librep-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-librep-fr.po l-librep-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-librep"
 test -d l-librep || mkdir l-librep
 test -d l-librep/fr || mkdir l-librep/fr
 test -d l-librep/fr/LC_MESSAGES || mkdir l-librep/fr/LC_MESSAGES
@@ -77,10 +64,10 @@ ${MSGFMT} -o l-librep/fr/LC_MESSAGES/prog.mo l-librep-fr.po
 
 # Test for presence of rep version 0.15.3 or newer.
 (rep --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: rep not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: rep not found"; exit 77; }
 case `rep --version | sed -e 's/^[^0-9]*//'` in
   0.[0-9] | 0.1[0-5] | 0.[0-9].* | 0.1[0-4].* | 0.15.[0-2] )
-    echo "Skipping test: rep version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: rep version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -108,10 +95,9 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles l-librep-prog.ok l-librep-prog.oku l-librep-prog.out"
 : ${DIFF=diff}
 cat <<\EOF > l-librep-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -132,7 +118,5 @@ if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 rep --no-rc --batch prog.jl > l-librep-prog.out || exit 1
   ${DIFF} l-librep-prog.oku l-librep-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-lua b/gettext-tools/tests/lang-lua
--- a/gettext-tools/tests/lang-lua
+++ b/gettext-tools/tests/lang-lua
@@ -5,10 +5,6 @@
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: lua, lua-gettext.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.lua"
 cat <<\EOF > prog.lua
 require("gettext")
 gettext.bindtextdomain("prog", "l-lua")
@@ -21,14 +17,10 @@ print(string.format(gettext.ngettext('a piece of cake', [[%d pieces of cake]], n
 print(string.format(_[==[%s is replaced by %s.]==], "FF", "EUR"))
 EOF
 
-tmpfiles="$tmpfiles l-lua-prog.tmp l-lua-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-lua-prog.tmp --omit-header --no-location prog.lua
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-lua-prog.tmp > l-lua-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-lua-prog.tmp --omit-header --no-location prog.lua || exit 1
+LC_ALL=C tr -d '\r' < l-lua-prog.tmp > l-lua-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-lua-prog.ok"
 cat <<\EOF > l-lua-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -47,7 +39,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-lua-prog.ok l-lua-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-lua-fr.po"
 cat <<\EOF > l-lua-fr.po
 msgid ""
 msgstr ""
@@ -68,17 +59,13 @@ msgid "%s is replaced by %s."
 msgstr "%s remplace %s."
 EOF
 
-tmpfiles="$tmpfiles l-lua-fr.po.tmp l-lua-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-lua-fr.po.tmp l-lua-fr.po l-lua-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-lua-fr.po.tmp > l-lua-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-lua-fr.po.tmp l-lua-fr.po l-lua-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-lua-fr.po.tmp > l-lua-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-lua-fr.po l-lua-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-lua"
 test -d l-lua || mkdir l-lua
 test -d l-lua/fr || mkdir l-lua/fr
 test -d l-lua/fr/LC_MESSAGES || mkdir l-lua/fr/LC_MESSAGES
@@ -89,14 +76,14 @@ ${MSGFMT} -o l-lua/fr/LC_MESSAGES/prog.mo l-lua-fr.po
 # Test for presence of lua version 5.0 or newer with gettext support.
 (lua -v) >/dev/null 2>/dev/null
 test $? -le 1 \
-  || { echo "Skipping test: lua not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: lua not found"; exit 77; }
 case `lua -v 2>&1 | sed -e 's/^[^0-9]*//'` in
   [5-9].*) ;;
-  *) echo "Skipping test: lua version too old"; rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: lua version too old"; exit 77;;
 esac
 { lua -v -l gettext > /dev/null 2>/dev/null; } \
   || { echo "Skipping test: lua gettext module not found"
-       rm -fr $tmpfiles; exit 77
+       exit 77
      }
 
 # Test which of the fr_FR locales are installed.
@@ -124,10 +111,9 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles l-lua-prog.ok l-lua-prog.oku l-lua-prog.out"
 : ${DIFF=diff}
 cat <<\EOF > l-lua-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -150,7 +136,5 @@ if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 lua -l gettext prog.lua > l-lua-prog.out || exit 1
   ${DIFF} l-lua-prog.oku l-lua-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-php b/gettext-tools/tests/lang-php
--- a/gettext-tools/tests/lang-php
+++ b/gettext-tools/tests/lang-php
@@ -5,10 +5,6 @@
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: mod_php4-core.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.php"
 cat <<\EOF > prog.php
 <?php
   setlocale (LC_ALL, "");
@@ -21,14 +17,10 @@ cat <<\EOF > prog.php
 ?>
 EOF
 
-tmpfiles="$tmpfiles l-php-prog.tmp l-php-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-php-prog.tmp --omit-header --no-location prog.php
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-php-prog.tmp > l-php-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-php-prog.tmp --omit-header --no-location prog.php || exit 1
+LC_ALL=C tr -d '\r' < l-php-prog.tmp > l-php-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-php-prog.ok"
 cat <<EOF > l-php-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -41,7 +33,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-php-prog.ok l-php-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-php-fr.po"
 cat <<\EOF > l-php-fr.po
 msgid ""
 msgstr "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -55,17 +46,13 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles l-php-fr.po.tmp l-php-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-php-fr.po.tmp l-php-fr.po l-php-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-php-fr.po.tmp > l-php-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-php-fr.po.tmp l-php-fr.po l-php-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-php-fr.po.tmp > l-php-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-php-fr.po l-php-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-php"
 test -d l-php || mkdir l-php
 test -d l-php/fr || mkdir l-php/fr
 test -d l-php/fr/LC_MESSAGES || mkdir l-php/fr/LC_MESSAGES
@@ -76,14 +63,14 @@ ${MSGFMT} -o l-php/fr/LC_MESSAGES/prog.mo l-php-fr.po
 # Test for presence of php version 4.0 or newer with gettext support.
 (php -v) >/dev/null 2>/dev/null
 test $? -le 1 \
-  || { echo "Skipping test: php not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: php not found"; exit 77; }
 case `php -v | sed -n -e 1p | sed -e 's/^[^0-9]*//'` in
   [4-9].*) ;;
-  *) echo "Skipping test: php version too old"; rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: php version too old"; exit 77;;
 esac
 { php -m | grep '^gettext$' >/dev/null; } \
   || { echo "Skipping test: php was built without gettext support"
-       rm -fr $tmpfiles; exit 77
+       exit 77
      }
 
 # Test which of the fr_FR locales are installed.
@@ -111,10 +98,9 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles l-php-prog.ok l-php-prog.oku l-php-prog.out"
 : ${DIFF=diff}
 cat <<\EOF > l-php-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -135,7 +121,5 @@ if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 php -q prog.php > l-php-prog.out || exit 1
   ${DIFF} l-php-prog.oku l-php-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
