Regenerated.

diff --git a/gettext-runtime/configure b/gettext-runtime/configure
--- a/gettext-runtime/configure
+++ b/gettext-runtime/configure
@@ -463,8 +463,8 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subdirs_all="$ac_subdirs_all libasprintf"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar docdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE YACC CPP EGREP HAVE_GCJ_IN_PATH HAVE_JAVAC_IN_PATH HAVE_JIKES_IN_PATH JAVAC CLASSPATH CLASSPATH_SEPARATOR HAVE_GCJ_C HAVE_JAVAC HAVE_JIKES JAR BUILDJAVA CSHARP_CHOICE HAVE_CSCC_IN_PATH HAVE_MCS_IN_PATH HAVE_CSC_IN_PATH HAVE_CSCC HAVE_MCS HAVE_CSC BUILDCSHARP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL RELOCATABLE LIBOBJS SET_RELOCATABLE RELOCATABLE_VIA_LD_TRUE RELOCATABLE_VIA_LD_FALSE MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE GLIBC2 CFLAG_VISIBILITY HAVE_VISIBILITY ALLOCA GLIBC21 INTL_MACOSX_LIBS LIBPTH LTLIBPTH LIBTHREAD LTLIBTHREAD LIBMULTITHREAD LTLIBMULTITHREAD HAVE_POSIX_PRINTF HAVE_ASPRINTF HAVE_SNPRINTF HAVE_WPRINTF LIBICONV LTLIBICONV INTLBISON BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATOBJEXT DATADIRNAME INSTOBJEXT GENCAT INTLOBJS INTL_LIBTOOL_SUFFIX_PREFIX INTLLIBS LIBINTL LTLIBINTL POSUB STDBOOL_H HAVE__BOOL ALLOCA_H GETOPT_H PERL CROSS_COMPILING LIBSCHED SUBDIR_libasprintf subdirs LTLIBOBJS'
+ac_subdirs_all="$ac_subdirs_all libasprintf glocale"
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar docdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE YACC JAVA_CHOICE CPP EGREP HAVE_GCJ_IN_PATH HAVE_JAVAC_IN_PATH HAVE_JIKES_IN_PATH JAVAC CLASSPATH CLASSPATH_SEPARATOR HAVE_GCJ_C HAVE_JAVAC HAVE_JIKES JAR BUILDJAVA CSHARP_CHOICE HAVE_CSCC_IN_PATH HAVE_MCS_IN_PATH HAVE_CSC_IN_PATH HAVE_CSCC HAVE_MCS HAVE_CSC BUILDCSHARP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL RELOCATABLE LIBOBJS SET_RELOCATABLE RELOCATABLE_VIA_LD_TRUE RELOCATABLE_VIA_LD_FALSE MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE GLIBC2 CFLAG_VISIBILITY HAVE_VISIBILITY ALLOCA GLIBC21 INTL_MACOSX_LIBS LIBPTH LTLIBPTH LIBTHREAD LTLIBTHREAD LIBMULTITHREAD LTLIBMULTITHREAD HAVE_POSIX_PRINTF HAVE_ASPRINTF HAVE_SNPRINTF HAVE_WPRINTF LIBICONV LTLIBICONV INTLBISON BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATOBJEXT DATADIRNAME INSTOBJEXT GENCAT INTLOBJS INTL_LIBTOOL_SUFFIX_PREFIX INTLLIBS LIBINTL LTLIBINTL POSUB STDBOOL_H HAVE__BOOL ALLOCA_H GETOPT_H PERL CROSS_COMPILING LIBSCHED ENABLE_LIBASPRINTF_TRUE ENABLE_LIBASPRINTF_FALSE ENABLE_GLOCALE_TRUE ENABLE_GLOCALE_FALSE subdirs LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1026,6 +1026,8 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --disable-java          do not build Java sources
+  --disable-native-java   do not compile Java to native executables
   --enable-csharp[=IMPL]  choose preferred C# implementation (pnet or mono)
   --enable-shared[=PKGS]
                           build shared libraries [default=yes]
@@ -1041,6 +1043,7 @@ Optional Features:
   --disable-threads       build without multithread safety
   --disable-rpath         do not hardcode runtime library paths
   --disable-libasprintf   do not build libasprintf
+  --disable-libglocale    do not build libglocale
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3183,6 +3186,28 @@ test -n "$YACC" || YACC="yacc"
 
 
 
+  echo "$as_me:$LINENO: checking whether to use Java" >&5
+echo $ECHO_N "checking whether to use Java... $ECHO_C" >&6
+  # Check whether --enable-java or --disable-java was given.
+if test "${enable_java+set}" = set; then
+  enableval="$enable_java"
+  JAVA_CHOICE="$enableval"
+else
+  JAVA_CHOICE=yes
+fi;
+  echo "$as_me:$LINENO: result: $JAVA_CHOICE" >&5
+echo "${ECHO_T}$JAVA_CHOICE" >&6
+  if test "$JAVA_CHOICE" = yes; then
+    # Check whether --enable-native-java or --disable-native-java was given.
+if test "${enable_native_java+set}" = set; then
+  enableval="$enable_native_java"
+  test "$enableval" != no || JAVA_CHOICE=bytecode
+fi;
+  fi
+
+
+
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3658,7 +3683,7 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test -n "$HAVE_JAVACOMP" && test -n "$JAR"; then
+if test -n "$HAVE_JAVACOMP" && test -n "$JAR" && test "$JAVA_CHOICE" != no; then
   BUILDJAVA=yes
 else
   BUILDJAVA=no
@@ -5023,7 +5048,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5026 "configure"' > conftest.$ac_ext
+  echo '#line 5051 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6371,7 +6396,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6374:" \
+echo "$as_me:6399:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7444,11 +7469,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7447: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7472: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7451: \$? = $ac_status" >&5
+   echo "$as_me:7476: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7702,11 +7727,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7705: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7730: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7709: \$? = $ac_status" >&5
+   echo "$as_me:7734: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7762,11 +7787,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7765: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7790: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7769: \$? = $ac_status" >&5
+   echo "$as_me:7794: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9963,7 +9988,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9966 "configure"
+#line 9991 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10061,7 +10086,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10064 "configure"
+#line 10089 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12286,11 +12311,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12289: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12314: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12293: \$? = $ac_status" >&5
+   echo "$as_me:12318: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12346,11 +12371,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12349: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12374: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12353: \$? = $ac_status" >&5
+   echo "$as_me:12378: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13710,7 +13735,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13713 "configure"
+#line 13738 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13808,7 +13833,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13811 "configure"
+#line 13836 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14666,11 +14691,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14669: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14694: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14673: \$? = $ac_status" >&5
+   echo "$as_me:14698: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14726,11 +14751,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14729: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14754: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14733: \$? = $ac_status" >&5
+   echo "$as_me:14758: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16787,11 +16812,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16790: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16794: \$? = $ac_status" >&5
+   echo "$as_me:16819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17045,11 +17070,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17048: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17073: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17052: \$? = $ac_status" >&5
+   echo "$as_me:17077: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17105,11 +17130,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17108: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17133: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17112: \$? = $ac_status" >&5
+   echo "$as_me:17137: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19306,7 +19331,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19309 "configure"
+#line 19334 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19404,7 +19429,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19407 "configure"
+#line 19432 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -27567,6 +27592,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <langinfo.h>
+#include <locale.h>
 int
 main ()
 {
@@ -33792,9 +33818,41 @@ if test "$CXX" = ":"; then
 fi
 
 
+if test -n "$SUBDIR_libasprintf"; then
+  ENABLE_LIBASPRINTF_TRUE=
+  ENABLE_LIBASPRINTF_FALSE='#'
+else
+  ENABLE_LIBASPRINTF_TRUE='#'
+  ENABLE_LIBASPRINTF_FALSE=
+fi
 
 
-subdirs="$subdirs libasprintf"
+# Check whether --enable-libglocale or --disable-libglocale was given.
+if test "${enable_libglocale+set}" = set; then
+  enableval="$enable_libglocale"
+  if test "$enableval" != no; then
+     SUBDIR_glocale=glocale
+   else
+     SUBDIR_glocale=
+   fi
+
+else
+  SUBDIR_glocale=glocale
+fi;
+
+
+if test -n "$SUBDIR_glocale"; then
+  ENABLE_GLOCALE_TRUE=
+  ENABLE_GLOCALE_FALSE='#'
+else
+  ENABLE_GLOCALE_TRUE='#'
+  ENABLE_GLOCALE_FALSE=
+fi
+
+
+
+
+subdirs="$subdirs libasprintf glocale"
 
 
           ac_config_files="$ac_config_files Makefile"
@@ -33954,6 +34012,20 @@ if test -z "${RELOCATABLE_VIA_LD_TRUE}" && test -z "${RELOCATABLE_VIA_LD_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"RELOCATABLE_VIA_LD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"RELOCATABLE_VIA_LD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_LIBASPRINTF_TRUE}" && test -z "${ENABLE_LIBASPRINTF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_LIBASPRINTF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_LIBASPRINTF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_GLOCALE_TRUE}" && test -z "${ENABLE_GLOCALE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_GLOCALE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_GLOCALE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -34393,7 +34465,7 @@ cat >>$CONFIG_STATUS <<_ACEOF
 AMDEP_TRUE="$AMDEP_TRUE" ac_aux_dir="$ac_aux_dir"
 # Capture the value of obsolete ALL_LINGUAS because we need it to compute
     # POFILES, UPDATEPOFILES, DUMMYPOFILES, GMOFILES, CATALOGS. But hide it
-    # from automake.
+    # from automake < 1.5.
     eval 'OBSOLETE_ALL_LINGUAS''="$ALL_LINGUAS"'
     # Capture the value of LINGUAS because we need it to compute CATALOGS.
     LINGUAS="${LINGUAS-%UNSET%}"
@@ -34551,6 +34623,7 @@ s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@am__fastdepCC_TRUE@,$am__fastdepCC_TRUE,;t t
 s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
 s,@YACC@,$YACC,;t t
+s,@JAVA_CHOICE@,$JAVA_CHOICE,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@HAVE_GCJ_IN_PATH@,$HAVE_GCJ_IN_PATH,;t t
@@ -34652,7 +34725,10 @@ s,@GETOPT_H@,$GETOPT_H,;t t
 s,@PERL@,$PERL,;t t
 s,@CROSS_COMPILING@,$CROSS_COMPILING,;t t
 s,@LIBSCHED@,$LIBSCHED,;t t
-s,@SUBDIR_libasprintf@,$SUBDIR_libasprintf,;t t
+s,@ENABLE_LIBASPRINTF_TRUE@,$ENABLE_LIBASPRINTF_TRUE,;t t
+s,@ENABLE_LIBASPRINTF_FALSE@,$ENABLE_LIBASPRINTF_FALSE,;t t
+s,@ENABLE_GLOCALE_TRUE@,$ENABLE_GLOCALE_TRUE,;t t
+s,@ENABLE_GLOCALE_FALSE@,$ENABLE_GLOCALE_FALSE,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
@@ -35390,11 +35466,12 @@ done
               test -n "$as_me" && echo "$as_me: setting ALL_LINGUAS in configure.in is obsolete" || echo "setting ALL_LINGUAS in configure.in is obsolete"
             fi
             ALL_LINGUAS_=`sed -e "/^#/d" -e "s/#.*//" "$ac_given_srcdir/$ac_dir/LINGUAS"`
-            # Hide the ALL_LINGUAS assigment from automake.
+            # Hide the ALL_LINGUAS assigment from automake < 1.5.
             eval 'ALL_LINGUAS''=$ALL_LINGUAS_'
             POMAKEFILEDEPS="$POMAKEFILEDEPS LINGUAS"
           else
             # The set of available languages was given in configure.in.
+            # Hide the ALL_LINGUAS assigment from automake < 1.5.
             eval 'ALL_LINGUAS''=$OBSOLETE_ALL_LINGUAS'
           fi
           # Compute POFILES
